# Configuration for GitHub's automatic release notes generator
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  # Exclude contributors from the release notes
  exclude:
    authors:
      - dependabot
      - bot

  # Define the categories and their associated labels/prefixes
  categories:
    - title: "🚀 New Features"
      labels:
        - "feature"
        - "feat"
    - title: "🐛 Bug Fixes"
      labels:
        - "fix"
        - "bug"
    - title: "🧹 Maintenance & Chores"
      labels:
        - "chore"
        - "docs"
        - "ci"
        - "build"
    - title: "⬆️ Dependency Updates"
      labels:
        - "dependencies"
