name: Global Standards & Alertss

on:
  pull_request:
    types: [edited, closed]

jobs:
  call-central-workflow:
    uses: zerofy-pro/pr-automation-center/.github/workflows/global-pr-standards.yml@main
    secrets: inherit 
