name: Build, Test, and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    permissions:
      contents: write 
      packages: write 
      security-events: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.15.2'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: |
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
            TAG="pr-${{ github.event.number }}"
          elif [[ $GITHUB_REF_TYPE == 'tag' ]]; then
            TAG=${GITHUB_REF_NAME}
          else
            TAG="edge"
          fi
          echo "VERSION=$TAG" >> $GITHUB_ENV

      - name: Run Tests and Build
        run: |
          make helm-lint
          make build
          make docker-build VERSION=${{ env.VERSION }}
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/zerofy-pro/rbac-collector:${{ env.VERSION }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) && '1' || '0' }}
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Push Docker Image
        if: github.event_name == 'push'
        run: make docker-push VERSION=${{ env.VERSION }}

      - name: Package Helm Chart for Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: make helm-package VERSION=${{ env.VERSION }}
      
      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./*.tgz
            ./trivy-results.sarif
          generate_release_notes: true